# Generated by gcc -D...  -dM -E - < /dev/null |grep RTE
#
# We disabled F16C and RDRAND explicitly because they are not
# supported by kvm and no real code depends on them.
#
# RTE_MACHINE_CPUFLAG_AES was disabled because Intel(R) Xeon(R) CPU
# E5-2667 v3 @ 3.20GHz doesn't support it. And the only place using
# AES is in examples/dpdk_qat/crypto.c
RTE_ENABLED_CPU_FEATURES = [
  'RTE_MACHINE_CPUFLAG_AVX',
  'RTE_MACHINE_CPUFLAG_AVX2',
  'RTE_MACHINE_CPUFLAG_FSGSBASE',
  'RTE_MACHINE_CPUFLAG_PCLMULQDQ',
  'RTE_MACHINE_CPUFLAG_SSE',
  'RTE_MACHINE_CPUFLAG_SSE2',
  'RTE_MACHINE_CPUFLAG_SSE3',
  'RTE_MACHINE_CPUFLAG_SSE4_1',
  'RTE_MACHINE_CPUFLAG_SSE4_2',
  'RTE_MACHINE_CPUFLAG_SSSE3',
]

RTE_CPU_DEFINES = RTE_ENABLED_CPU_FEATURES + [
  'RTE_COMPILE_TIME_CPUFLAGS=' + ','.join(RTE_ENABLED_CPU_FEATURES),
]

DPDK_X64_CFLAGS = ['-D' + f for f in RTE_CPU_DEFINES] + [
  # Compiling rte_memcpy.h requires CPU specific optimizations
  '-msse4.2',
  '-mavx2',
]

DPDK_CONFIG_CFLAGS = [
  # Make sure rte_config.h is implicitly included
  '-include',
  'rte_config.h',
] + DPDK_X64_CFLAGS
