// Generated by gcc -D...  -dM -E - < /dev/null |grep RTE

// We disabled F16C and RDRAND explicitly because they are not
// supported by kvm and no real code depends on them.

// RTE_MACHINE_CPUFLAG_AES was disabled because Intel(R) Xeon(R) CPU
// E5-2667 v3 @ 3.20GHz doesn't support it. And the only place using
// AES is in examples/dpdk_qat/crypto.c

#define RTE_MACHINE_CPUFLAG_SSSE3 1
#define RTE_MACHINE_CPUFLAG_PCLMULQDQ 1
#define RTE_MACHINE_CPUFLAG_SSE 1
#define RTE_MACHINE_CPUFLAG_SSE2 1
#define RTE_MACHINE_CPUFLAG_SSE3 1
#define RTE_MACHINE_CPUFLAG_AVX 1
#define RTE_MACHINE_CPUFLAG_SSE4_1 1
#define RTE_MACHINE_CPUFLAG_SSE4_2 1
#define RTE_MACHINE_CPUFLAG_FSGSBASE 1
#define RTE_MACHINE_CPUFLAG_AVX2 1
#define RTE_COMPILE_TIME_CPUFLAGS RTE_CPUFLAG_SSE,RTE_CPUFLAG_SSE2,RTE_CPUFLAG_SSE3,RTE_CPUFLAG_SSSE3,RTE_CPUFLAG_SSE4_1,RTE_CPUFLAG_SSE4_2,RTE_CPUFLAG_PCLMULQDQ,RTE_CPUFLAG_AVX,RTE_CPUFLAG_FSGSBASE,RTE_CPUFLAG_AVX2

